version: '3.8'

services:
  backend:
    build: ./backend/
    container_name: vehicle_backend
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vehicle_db
      - SECRET_KEY=dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    container_name: vehicle_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vehicle_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
